CREATE DATABASE postgres;

CREATE USER stats_user WITH PASSWORD 'stats_password';

GRANT ALL PRIVILEGES ON DATABASE stats_db TO stats_user;

\c stats_db;

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_hits_timestamp ON hits(timestamp);
CREATE INDEX idx_hits_uri ON hits(uri);
CREATE INDEX idx_hits_app ON hits(app_name);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO stats_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO stats_user;