# Stage 1: Build
FROM maven:3.8.4-eclipse-temurin-17 AS build
WORKDIR /app

# Копируем только необходимые файлы
COPY pom.xml .
COPY main-service/pom.xml main-service/pom.xml
COPY main-service/src main-service/src

# Собираем проект (только main-service и его зависимости)
RUN mvn clean package -pl main-service -am -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/main-service/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]